# Generated by Django 2.0.4 on 2018-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotName', models.CharField(max_length=20)),
                ('projectCode', models.CharField(max_length=20)),
                ('reel', models.CharField(max_length=10)),
                ('seq', models.CharField(max_length=10)),
                ('clientCode', models.CharField(max_length=20)),
                ('sourceStatus', models.CharField(max_length=20)),
                ('sourceType', models.CharField(max_length=20)),
                ('shotStatus', models.CharField(max_length=20)),
                ('rotoStatus', models.CharField(max_length=20)),
                ('cpStatus', models.CharField(max_length=20)),
                ('clientid', models.CharField(max_length=20)),
                ('clientFFrame', models.IntegerField(verbose_name=11)),
                ('clientLFrame', models.IntegerField(verbose_name=11)),
                ('clientFrames', models.IntegerField(verbose_name=11)),
                ('activeFFrame', models.IntegerField(verbose_name=11)),
                ('activeLFrame', models.IntegerField(verbose_name=11)),
                ('activeFrames', models.IntegerField(verbose_name=11)),
            ],
        ),
    ]
